name: PHPUnit Tests with MySQL

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run PHPUnit Tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: test_database
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      -   uses: actions/checkout@v4
      -   uses: php-actions/composer@v6 # Use composer or alternative dependency management

      - name: Wait for MySQL Service
        run: |
          echo "Waiting for MySQL service to become available..."
          until mysql -h127.0.0.1 -uroot -proot_password -e ";" &>/dev/null; do
            echo "MySQL is unavailable - sleeping"
            sleep 5
          done
          echo "MySQL is available"

      - name: Run PHPUnit Tests
        run: vendor/bin/phpunit --colors=always --coverage-text 

