name: PHPUnit Tests

on: [push, pull_request]

jobs:
  phpunit:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_database
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start MySQL Service
        run: sudo /etc/init.d/mysql start

      - name: Wait for MySQL to start
        run: sleep 5

      - name: Create MySQL Database
        run: |
          echo "Creating MySQL database..."
          mysql -h 127.0.0.1 -u root -proot -e 'CREATE DATABASE IF NOT EXISTS test_database;' || exit 1
          sleep 5  # Add a 5-second pause after creating the database

      - name: Load database structure and data
        run: mysql -h 127.0.0.1 -u root -proot test_database < tests/test_database.sql

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: pdo_mysql
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

      - name: Debug MySQL Connection
        run: |
          echo "Attempting MySQL connection..."
          mysql -h 127.0.0.1 -u root -proot -e 'SELECT 1' || exit 1

      - name: Run PHPUnit
        run: vendor/bin/phpunit --configuration phpunit.xml
