name: PHPUnit Tests

on: [push, pull_request]

jobs:
  phpunit:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: 'password' # Set a password for the root user
          MYSQL_DATABASE: test_database
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
      - name: Start MySQL Service
        run: sudo /etc/init.d/mysql start

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: pdo_mysql
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

      - name: Debug MySQL Connection
        run: |
          echo "Attempting MySQL connection..."
          mysql -h localhost -u root -ppassword -e 'SELECT 1' || exit 1 # Use the specified password for the root user

      - name: Run PHPUnit
        run: vendor/bin/phpunit --configuration phpunit.xml
